// components/todoList.tsx
"use client";

import { useState, useEffect, FormEvent, useRef } from "react";
import {
  DndContext,
  closestCenter,
  KeyboardSensor,
  PointerSensor,
  useSensor,
  useSensors,
} from '@dnd-kit/core';
import {
  arrayMove,
  SortableContext,
  sortableKeyboardCoordinates,
  verticalListSortingStrategy,
} from '@dnd-kit/sortable';
import { useSortable } from '@dnd-kit/sortable';
import { CSS } from '@dnd-kit/utilities';

import { Checkbox } from "@/components/ui/checkbox";
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";

interface Todo {
  id: string;
  text: string;
  completed: boolean;
  childIds: string[];
  parentIds: string[];
  assignedTo?: string;
  deadline?: string;
}

// Separat komponent för varje sorterbart objekt
interface SortableItemProps {
  id: string;
  todo: Todo;
  selectedIndex: number | null;
  index: number;
  handleToggleTodo: (id: string) => void;
  setSelectedIndex: (index: number) => void;
  level?: number;
  todos: Todo[];
}

function SortableItem({ id, todo, selectedIndex, index, handleToggleTodo, setSelectedIndex, level = 0, todos }: SortableItemProps) {
  const {
    attributes,
    listeners,
    setNodeRef,
    transform,
    transition,
  } = useSortable({ id });

  const style = {
    transform: CSS.Transform.toString(transform),
    transition,
    marginLeft: `${level * 2}rem`,
  };

  const childTasks = todo.childIds
    .map((childId: string) => todos.find((t: Todo) => t.id === childId))
    .filter((t): t is Todo => t !== undefined);

  return (
    <>
      <div
        ref={setNodeRef}
        style={style}
        {...attributes}
        {...listeners}
        className={`flex flex-col p-2 rounded w-full ${selectedIndex === index ? 'bg-gray-200 dark:bg-gray-700' : ''}`}
        onClick={() => setSelectedIndex(index)}
      >
        <div className="flex items-center space-x-2">
          <Checkbox
            id={todo.id}
            checked={todo.completed}
            onCheckedChange={() => handleToggleTodo(todo.id)}
          />
          <Label
            htmlFor={todo.id}
            className={`text-sm font-medium leading-none ${
              todo.completed ? "line-through text-gray-500" : ""
            } peer-disabled:cursor-not-allowed peer-disabled:opacity-70`}
          >
            {todo.text}
          </Label>
        </div>
        <div className="flex items-center text-xs mt-1 ml-6 text-gray-500">
          {todo.assignedTo && (
            <span className="mr-2">Tilldelad: {todo.assignedTo}</span>
          )}
          {todo.deadline && (
            <span>Deadline: {todo.deadline}</span>
          )}
        </div>
      </div>
      {childTasks.map((subtask, subIndex) => (
        <SortableItem
          key={subtask.id}
          id={subtask.id}
          todo={subtask}
          selectedIndex={selectedIndex}
          index={subIndex}
          handleToggleTodo={handleToggleTodo}
          setSelectedIndex={setSelectedIndex}
          level={level + 1}
          todos={todos}
        />
      ))}
    </>
  );
}



export default function TodoList() {
  const [todos, setTodos] = useState<Todo[]>([
    {
      id: "todo11",
      text: "Är den här avcheckad så fungerar allt",
      completed: true,
      childIds: [],
      parentIds: [],
    },
    {
      id: "todo0",
      text: "Går att bygga image via DOCKERFILE",
      completed: true,
      childIds: [],
      parentIds: [],
    },
    // ... other todos ...
  ]);
  const [selectedIndex, setSelectedIndex] = useState<number | null>(null);
  const [newTodoText, setNewTodoText] = useState("");
  const [newAssignedTo, setNewAssignedTo] = useState("");
  const [newDeadline, setNewDeadline] = useState("");
  const [editText, setEditText] = useState("");
  const [editAssignedTo, setEditAssignedTo] = useState("");
  const [editDeadline, setEditDeadline] = useState("");
  const [editingId, setEditingId] = useState<string | null>(null);
  const inputRef = useRef<HTMLInputElement>(null);

  const sensors = useSensors(
    useSensor(PointerSensor),
    useSensor(KeyboardSensor, {
      coordinateGetter: sortableKeyboardCoordinates,
    })
  );

  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if (editingId) {
        // Ignore keyboard shortcuts when editing
        return;
      }
      
      if (e.key === "Escape") {
        if (document.activeElement === inputRef.current) {
          inputRef.current?.blur();
        }
      }
      
      if (document.activeElement instanceof HTMLInputElement) {
        return;
      }

      if (e.key === 'i') {
        e.preventDefault();
        inputRef.current?.focus();
        return;
      }
      
      if (selectedIndex === null) {
        if (e.key === 'j' || e.key === 'k') {
          setSelectedIndex(0);
        }
        return;
      }

      switch (e.key) {
        case "j":
          setSelectedIndex((prev) => (prev === null ? 0 : Math.min(todos.length - 1, prev + 1)));
          break;
        case "k":
          setSelectedIndex((prev) => (prev === null ? 0 : Math.max(0, prev - 1)));
          break;
        case "w":
          moveTodo(-1);
          break;
        case "s":
          moveTodo(1);
          break;
        case "g":
          setSelectedIndex(0);
          break;
        case "G":
          setSelectedIndex(todos.length - 1);
          break;
        case "x":
          handleDeleteTodo();
          break;
        case "I":
          if (selectedIndex !== null) {
            const parentTodo = todos[selectedIndex];
            const newSubtask: Todo = {
              id: `todo-${Date.now()}`,
              text: "New Subtask",
              completed: false,
              childIds: [],
              parentIds: [parentTodo.id],
            };
            setTodos(prev => [
              ...prev.map(todo => 
                todo.id === parentTodo.id 
                  ? { ...todo, childIds: [...todo.childIds, newSubtask.id] } 
                  : todo
              ),
              newSubtask
            ]);
          }
          break;
        case " ":
          e.preventDefault();
          if (selectedIndex !== null) {
            handleToggleTodo(todos[selectedIndex].id);
          }
          break;
        case "e":
          if (selectedIndex !== null) {
            const todo = todos[selectedIndex];
            setEditText(todo.text);
            setEditAssignedTo(todo.assignedTo || "");
            setEditDeadline(todo.deadline || "");
            setEditingId(todo.id);
          }
          break;
      }
    };

    window.addEventListener("keydown", handleKeyDown);
    return () => {
      window.removeEventListener("keydown", handleKeyDown);
    };
  }, [todos, selectedIndex, editingId, handleDeleteTodo, handleToggleTodo, moveTodo]);

  const moveTodo = (direction: number) => {
    if (selectedIndex === null) return;
    const newIndex = selectedIndex + direction;
    if (newIndex < 0 || newIndex >= todos.length) return;

    const newTodos = Array.from(todos);
    const [movedTodo] = newTodos.splice(selectedIndex, 1);
    newTodos.splice(newIndex, 0, movedTodo);
    setTodos(newTodos);
    setSelectedIndex(newIndex);
  };

  const handleToggleTodo = (id: string) => {
    setTodos(prevTodos => {
      const newTodos = [...prevTodos];
      const todo = newTodos.find(t => t.id === id);
      if (todo) {
        todo.completed = !todo.completed;
        const toggleChildren = (childIds: string[]) => {
          childIds.forEach(childId => {
            const child = newTodos.find(t => t.id === childId);
            if (child) {
              child.completed = todo.completed;
              toggleChildren(child.childIds);
            }
          });
        };
        toggleChildren(todo.childIds);
      }
      return newTodos;
    });
  };

  const handleDeleteTodo = () => {
    if (selectedIndex === null) return;
    const todoToDelete = todos[selectedIndex];
    const newTodos = todos.filter(todo => todo.id !== todoToDelete.id && !todoToDelete.childIds.includes(todo.id));
    setTodos(newTodos);
    if (newTodos.length === 0) {
      setSelectedIndex(null);
    } else if (selectedIndex >= newTodos.length) {
      setSelectedIndex(newTodos.length - 1);
    }
  };

  const handleAddTodo = (e: FormEvent) => {
    e.preventDefault();
    if (newTodoText.trim() === "") return;
    const newTodo: Todo = {
      id: `todo-${Date.now()}`,
      text: newTodoText,
      completed: false,
      childIds: [],
      parentIds: [],
      assignedTo: newAssignedTo.trim() ? newAssignedTo : undefined,
      deadline: newDeadline.trim() ? newDeadline : undefined,
    };
    setTodos([...todos, newTodo]);
    setNewTodoText("");
    setNewAssignedTo("");
    setNewDeadline("");
  };

  function handleDragEnd(event: any) {
    const { active, over } = event;

    if (active.id !== over.id) {
      setTodos((items) => {
        const activeIndex = items.findIndex(item => item.id === active.id);
        const overIndex = items.findIndex(item => item.id === over.id);
        const newItems = arrayMove(items, activeIndex, overIndex);

        const activeTodo = newItems.find(item => item.id === active.id);
        const overTodo = newItems.find(item => item.id === over.id);

        if (activeTodo && overTodo) {
          // Remove from old parent
          activeTodo.parentIds.forEach(parentId => {
            const parent = newItems.find(item => item.id === parentId);
            if (parent) {
              parent.childIds = parent.childIds.filter(childId => childId !== active.id);
            }
          });

          // Add to new parent
          activeTodo.parentIds = [over.id];
          overTodo.childIds.push(active.id);
        }

        return newItems;
      });
    }
  }

  // Only count top-level tasks for progress
  const topLevelTodos = todos.filter(todo => todo.parentIds.length === 0);
  const completedCount = topLevelTodos.filter(todo => todo.completed).length;
  const totalCount = topLevelTodos.length;
  const progressPercentage = totalCount > 0 ? Math.round((completedCount / totalCount) * 100) : 0;
  
  const [filter, setFilter] = useState<'all' | 'active' | 'completed'>('all');
  const [sort, setSort] = useState<'date' | 'assigned' | 'deadline'>('date');
  
  // Filter tasks
  let visibleTodos = todos.filter(todo => {
    if (filter === 'active') return !todo.completed;
    if (filter === 'completed') return todo.completed;
    return true;
  });
  
  // Sort tasks
  visibleTodos = [...visibleTodos].sort((a, b) => {
    if (sort === 'assigned') {
      const aAssigned = a.assignedTo || 'ZZZ';
      const bAssigned = b.assignedTo || 'ZZZ';
      return aAssigned.localeCompare(bAssigned);
    }
    if (sort === 'deadline') {
      const aDeadline = a.deadline || '9999-12-31';
      const bDeadline = b.deadline || '9999-12-31';
      return aDeadline.localeCompare(bDeadline);
    }
    // Default sort by creation date (id contains timestamp)
    return a.id.localeCompare(b.id);
  });
  
  return (
    <div>
      <div className="mb-4">
        <div className="flex justify-between items-center mb-1">
          <span className="text-sm font-medium">Framsteg: {progressPercentage}%</span>
          <span className="text-sm text-gray-500">{completedCount}/{totalCount} uppgifter</span>
        </div>
        <div className="h-2 bg-gray-200 rounded-full">
          <div 
            className="h-full bg-green-500 rounded-full" 
            style={{ width: `${progressPercentage}%` }}
          ></div>
        </div>
      </div>
      
      <div className="flex justify-between mb-4">
        <div className="flex space-x-2">
          <Button 
            variant={filter === 'all' ? 'default' : 'outline'}
            onClick={() => setFilter('all')}
          >
            Alla
          </Button>
          <Button 
            variant={filter === 'active' ? 'default' : 'outline'}
            onClick={() => setFilter('active')}
          >
            Aktiva
          </Button>
          <Button 
            variant={filter === 'completed' ? 'default' : 'outline'}
            onClick={() => setFilter('completed')}
          >
            Klara
          </Button>
        </div>
        
        <div className="flex space-x-2">
          <Button 
            variant={sort === 'date' ? 'default' : 'outline'}
            onClick={() => setSort('date')}
          >
            Datum
          </Button>
          <Button 
            variant={sort === 'assigned' ? 'default' : 'outline'}
            onClick={() => setSort('assigned')}
          >
            Tilldelad
          </Button>
          <Button 
            variant={sort === 'deadline' ? 'default' : 'outline'}
            onClick={() => setSort('deadline')}
          >
            Deadline
          </Button>
        </div>
      </div>
      
      <DndContext 
        sensors={sensors}
        collisionDetection={closestCenter}
        onDragEnd={handleDragEnd}
      >
        <SortableContext 
          items={todos.map(todo => todo.id)}
          strategy={verticalListSortingStrategy}
        >
      <div className="flex flex-col items-start space-y-2 mb-4">
        {visibleTodos.filter(todo => todo.parentIds.length === 0).map((todo, index) => {
          if (editingId === todo.id) {
            return (
              <div key={`edit-${todo.id}`} className="flex flex-col p-2 rounded w-full bg-gray-100 dark:bg-gray-800 mb-2">
                <div className="flex flex-col space-y-2">
                  <Input 
                    type="text" 
                    value={editText}
                    onChange={(e) => setEditText(e.target.value)}
                    className="mb-2"
                  />
                  <div className="flex space-x-2">
                    <Input 
                      type="text"
                      placeholder="Tilldelad"
                      value={editAssignedTo}
                      onChange={(e) => setEditAssignedTo(e.target.value)}
                      className="flex-1"
                    />
                    <Input 
                      type="date"
                      value={editDeadline}
                      onChange={(e) => setEditDeadline(e.target.value)}
                      className="flex-1"
                    />
                  </div>
                  <div className="flex space-x-2">
                    <Button 
                      onClick={() => {
                        setTodos(prev => prev.map(t => 
                          t.id === todo.id 
                            ? { ...t, text: editText, assignedTo: editAssignedTo.trim() || undefined, deadline: editDeadline.trim() || undefined } 
                            : t
                        ));
                        setEditingId(null);
                      }}
                    >
                      Spara
                    </Button>
                    <Button variant="outline" onClick={() => setEditingId(null)}>
                      Avbryt
                    </Button>
                  </div>
                </div>
              </div>
            );
          }
          return (
            <SortableItem 
              key={todo.id} 
              id={todo.id} 
              todo={todo} 
              selectedIndex={selectedIndex} 
              index={index} 
              handleToggleTodo={handleToggleTodo}
              setSelectedIndex={setSelectedIndex}
              todos={todos}
            />
          );
        })}
      </div>
        </SortableContext>
      </DndContext>
      <form onSubmit={handleAddTodo} className="flex flex-col w-full max-w-md space-y-2">
        <div className="flex space-x-2">
          <Input 
            ref={inputRef}
            type="text" 
            placeholder="Ny uppgift..." 
            value={newTodoText}
            onChange={(e) => setNewTodoText(e.target.value)}
            className="flex-1"
          />
          <Button type="submit">Lägg till</Button>
        </div>
        <div className="flex space-x-2">
          <Input 
            type="text"
            placeholder="Tilldelad (valfritt)"
            value={newAssignedTo}
            onChange={(e) => setNewAssignedTo(e.target.value)}
            className="flex-1"
          />
          <Input 
            type="date"
            value={newDeadline}
            onChange={(e) => setNewDeadline(e.target.value)}
            className="flex-1"
          />
        </div>
      </form>
    </div>
  );
}

// nuxt-plan/src/components/todoList.vue
<template>
  <div>
    <div class="mb-4">
      <div class="flex justify-between items-center mb-1">
        <span class="text-sm font-medium">
          Framsteg: {{ progressPercentage }}%
        </span>
        <span class="text-sm text-gray-500">
          {{ completedCount }}/{{ totalCount }} uppgifter
        </span>
      </div>
      <div class="h-2 bg-gray-200 rounded-full">
        <div
          class="h-full bg-green-500 rounded-full"
          :style="{ width: `${progressPercentage}%` }"
        ></div>
      </div>
    </div>

    <div class="flex justify-between mb-4">
      <div class="flex space-x-2">
        <Button
          :variant="filter === 'all' ? 'default' : 'outline'"
          @click="setFilter('all')"
        >
          Alla
        </Button>
        <Button
          :variant="filter === 'active' ? 'default' : 'outline'"
          @click="setFilter('active')"
        >
          Aktiva
        </Button>
        <Button
          :variant="filter === 'completed' ? 'default' : 'outline'"
          @click="setFilter('completed')"
        >
          Klara
        </Button>
      </div>

      <div class="flex space-x-2">
        <Button
          :variant="sort === 'date' ? 'default' : 'outline'"
          @click="setSort('date')"
        >
          Datum
        </Button>
        <Button
          :variant="sort === 'assigned' ? 'default' : 'outline'"
          @click="setSort('assigned')"
        >
          Tilldelad
        </Button>
        <Button
          :variant="sort === 'deadline' ? 'default' : 'outline'"
          @click="setSort('deadline')"
        >
          Deadline
        </Button>
      </div>
    </div>

    <draggable
      v-model="topLevelTodosSortable"
      tag="div"
      class="flex flex-col items-start space-y-2 mb-4"
      item-key="id"
      @end="handleDragEnd"
    >
      <template #item="{ element: todo, index }">
        <div v-if="editingId === todo.id" class="flex flex-col p-2 rounded w-full bg-gray-100 dark:bg-gray-800 mb-2">
          <div class="flex flex-col space-y-2">
            <Input
              type="text"
              v-model="editText"
              class="mb-2"
            />
            <div class="flex space-x-2">
              <Input
                type="text"
                placeholder="Tilldelad"
                v-model="editAssignedTo"
                class="flex-1"
              />
              <Input
                type="date"
                v-model="editDeadline"
                class="flex-1"
              />
            </div>
            <div class="flex space-x-2">
              <Button
                @click="() => {
                  setTodos(todos.map((t) =>
                    t.id === todo.id
                      ? {
                          ...t,
                          text: editText,
                          assignedTo:
                            editAssignedTo.trim() || undefined,
                          deadline:
                            editDeadline.trim() || undefined,
                        }
                      : t,
                  ));
                  editingId = null;
                }"
              >
                Spara
              </Button>
              <Button
                variant="outline"
                @click="editingId = null"
              >
                Avbryt
              </Button>
            </div>
          </div>
        </div>
        <SortableItem
          v-else
          :id="todo.id"
          :todo="todo"
          :selected-index="selectedIndex"
          :index="index"
          @toggle-todo="handleToggleTodo"
          @set-selected-index="setSelectedIndex"
          :todos="todos"
        />
      </template>
    </draggable>
    <form
      @submit.prevent="handleAddTodo"
      class="flex flex-col w-full max-w-md space-y-2"
    >
      <div class="flex space-x-2">
        <Input
          ref="inputRef"
          type="text"
          placeholder="Ny uppgift..."
          v-model="newTodoText"
          class="flex-1"
        />
        <Button type="submit">Lägg till</Button>
      </div>
      <div class="flex space-x-2">
        <Input
          type="text"
          placeholder="Tilldelad (valfritt)"
          v-model="newAssignedTo"
          class="flex-1"
        />
        <Input
          type="date"
          v-model="newDeadline"
          class="flex-1"
        />
      </div>
    </form>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted, onUnmounted } from 'vue';
import draggable from 'vue-draggable-plus'; // Import draggable component
import type { Todo } from '~/types/todo-entity';
import Button from '@/components/ui/button.vue';
import Checkbox from '@/components/ui/checkbox.vue';
import Input from '@/components/ui/input.vue';
import Label from '@/components/ui/label.vue';
import SortableItem from '@/components/SortableItem.vue';

const todos = ref<Todo[]>(
  [
    {
      id: "todo11",
      text: "Är den här avcheckad så fungerar allt",
      completed: true,
      childIds: [],
      parentIds: [],
    },
    {
      id: "todo0",
      text: "Går att bygga image via DOCKERFILE",
      completed: true,
      childIds: [],
      parentIds: [],
    },
  ]
);

const selectedIndex = ref<number | null>(null);
const newTodoText = ref("");
const newAssignedTo = ref("");
const newDeadline = ref("");
const editText = ref("");
const editAssignedTo = ref("");
const editDeadline = ref("");
const editingId = ref<string | null>(null);
const inputRef = ref<HTMLInputElement | null>(null);

const handleDeleteTodo = () => {
  if (selectedIndex.value === null) return;
  const todoToDelete = todos.value[selectedIndex.value];
  const newTodos = todos.value.filter(
    (todo) =>
      todo.id !== todoToDelete.id && !todoToDelete.childIds.includes(todo.id),
  );
  todos.value = newTodos;
  if (newTodos.length === 0) {
    selectedIndex.value = null;
  } else if (selectedIndex.value >= newTodos.length) {
    selectedIndex.value = newTodos.length - 1;
  }
};

const handleToggleTodo = (id: string) => {
  const newTodos = [...todos.value];
  const todo = newTodos.find((t) => t.id === id);
  if (todo) {
    todo.completed = !todo.completed;
    const toggleChildren = (childIds: string[]) => {
      childIds.forEach((childId) => {
        const child = newTodos.find((t) => t.id === childId);
        if (child) {
          child.completed = todo.completed;
          toggleChildren(child.childIds);
        }
      });
    };
    toggleChildren(todo.childIds);
  }
  todos.value = newTodos;
};

const moveTodo = (direction: number) => {
  if (selectedIndex.value === null) return;
  const newIndex = selectedIndex.value + direction;
  if (newIndex < 0 || newIndex >= todos.value.length) return;

  const newTodos = Array.from(todos.value);
  const [movedTodo] = newTodos.splice(selectedIndex.value, 1);
  newTodos.splice(newIndex, 0, movedTodo);
  todos.value = newTodos;
  selectedIndex.value = newIndex;
};

const handleDragEnd = (event: { newIndex: number, oldIndex: number }) => {
  const { newIndex, oldIndex } = event;

  if (newIndex === oldIndex) return;

  const movedTodo = topLevelTodosSortable.value[oldIndex];
  const targetTodo = topLevelTodosSortable.value[newIndex];

  // Find the actual index of these todos in the main `todos` array
  const oldActualIndex = todos.value.findIndex(t => t.id === movedTodo.id);
  const newActualIndex = todos.value.findIndex(t => t.id === targetTodo.id);

  // Temporarily adjust `todos` array to reflect the new order without changing parent/child relationships yet
  const reorderedMainTodos = [...todos.value];
  const [removed] = reorderedMainTodos.splice(oldActualIndex, 1);
  reorderedMainTodos.splice(newActualIndex, 0, removed);

  // Update parent/child relationships based on the new visual order
  // This part is simplified and might need more complex logic for nested DND
  // For now, assume reordering only affects top-level todos visually.
  // A more robust solution would involve finding the new parent or sibling if dropped on another item.
  
  todos.value = reorderedMainTodos;
};

onMounted(() => {
  const handleKeyDown = (e: KeyboardEvent) => {
    if (editingId.value) {
      return;
    }

    if (e.key === "Escape") {
      if (document.activeElement === inputRef.value) {
        inputRef.value?.blur();
      }
    }

    if (document.activeElement instanceof HTMLInputElement) {
      return;
    }

    if (e.key === "i") {
      e.preventDefault();
      inputRef.value?.focus();
      return;
    }

    if (selectedIndex.value === null) {
      if (e.key === "j" || e.key === "k") {
        selectedIndex.value = 0;
      }
      return;
    }

    switch (e.key) {
      case "j":
        selectedIndex.value = Math.min(todos.value.length - 1, (selectedIndex.value === null ? 0 : selectedIndex.value) + 1);
        break;
      case "k":
        selectedIndex.value = Math.max(0, (selectedIndex.value === null ? 0 : selectedIndex.value) - 1);
        break;
      case "w":
        moveTodo(-1);
        break;
      case "s":
        moveTodo(1);
        break;
      case "g":
        selectedIndex.value = 0;
        break;
      case "G":
        selectedIndex.value = todos.value.length - 1;
        break;
      case "x":
        handleDeleteTodo();
        break;
      case "I":
        if (selectedIndex.value !== null) {
          const parentTodo = todos.value[selectedIndex.value];
          const newSubtask: Todo = {
            id: `todo-${Date.now()}`,
            text: "New Subtask",
            completed: false,
            childIds: [],
            parentIds: [parentTodo.id],
          };
          todos.value = [
            ...todos.value.map((todo) =>
              todo.id === parentTodo.id
                ? { ...todo, childIds: [...todo.childIds, newSubtask.id] }
                : todo,
            ),
            newSubtask,
          ];
        }
        break;
      case " ":
        e.preventDefault();
        if (selectedIndex.value !== null) {
          handleToggleTodo(todos.value[selectedIndex.value].id);
        }
        break;
      case "e":
        if (selectedIndex.value !== null) {
          const todo = todos.value[selectedIndex.value];
          editText.value = todo.text;
          editAssignedTo.value = todo.assignedTo || "";
          editDeadline.value = todo.deadline || "";
          editingId.value = todo.id;
        }
        break;
    }
  };

  window.addEventListener("keydown", handleKeyDown);
});

onUnmounted(() => {
  // No specific cleanup for addEventListener if it's set globally in onMounted and auto-removed by Vue
});

const handleAddTodo = () => {
  if (newTodoText.value.trim() === "") return;
  const newTodo: Todo = {
    id: `todo-${Date.now()}`,
    text: newTodoText.value,
    completed: false,
    childIds: [],
    parentIds: [],
    assignedTo: newAssignedTo.value.trim() ? newAssignedTo.value : undefined,
    deadline: newDeadline.value.trim() ? newDeadline.value : undefined,
  };
  todos.value = [...todos.value, newTodo];
  newTodoText.value = "";
  newAssignedTo.value = "";
  newDeadline.value = "";
};

const topLevelTodosSortable = computed<Todo[]>({ // Use a writable computed for v-model with draggable
  get: () => todos.value.filter((todo) => todo.parentIds.length === 0),
  set: (newValue: Todo[]) => {
    // This setter is called by vue-draggable-plus after a drag operation.
    // We need to reorder the main `todos.value` array to reflect the new order of top-level items.
    // This is a simplified reordering for top-level only.

    const oldOrderTopLevelIds = topLevelTodosSortable.value.map(t => t.id);
    const newOrderTopLevelIds = newValue.map(t => t.id);

    // Create a map for quick lookup of goals by ID
    const todoMap = new Map<string, Todo>();
    todos.value.forEach(todo => todoMap.set(todo.id, todo));

    // Reconstruct the main todos array ensuring order of top-level items and keeping children associated
    let reorderedTodos: Todo[] = [];
    const processedIds = new Set<string>();

    newOrderTopLevelIds.forEach(id => {
      const todo = todoMap.get(id);
      if (todo && !processedIds.has(id)) {
        reorderedTodos.push(todo);
        processedIds.add(id);
        // Add children directly after if they belong to this parent and are not already processed
        // This part would need more sophisticated logic for complex nested sorting
        todo.childIds.forEach(childId => {
          if (todoMap.has(childId) && !processedIds.has(childId)) {
            reorderedTodos.push(todoMap.get(childId)!);
            processedIds.add(childId);
          }
        });
      }
    });
    
    // Add any remaining todos that were not top-level or children of reordered top-level items
    // This is a fallback and might need refinement for full nested drag-and-drop hierarchy.
    todos.value.forEach(todo => {
      if (!processedIds.has(todo.id)) {
        reorderedTodos.push(todo);
      }
    });

    todos.value = reorderedTodos;
  }
});

const completedCount = computed(() =>
  topLevelTodosSortable.value.filter((todo) => todo.completed).length
);

const totalCount = computed(() => topLevelTodosSortable.value.length);

const progressPercentage = computed(() =>
  totalCount.value > 0 ? Math.round((completedCount.value / totalCount.value) * 100) : 0
);

const filter = ref<"all" | "active" | "completed">("all");
const sort = ref<"date" | "assigned" | "deadline">("date");

const setFilter = (value: "all" | "active" | "completed") => {
  filter.value = value;
};

const setSort = (value: "date" | "assigned" | "deadline") => {
  sort.value = value;
};

const visibleTodos = computed(() => {
  let filtered = todos.value.filter((todo) => {
    if (filter.value === "active") return !todo.completed;
    if (filter.value === "completed") return todo.completed;
    return true;
  });

  // Sort tasks
  filtered = [...filtered].sort((a, b) => {
    if (sort.value === "assigned") {
      const aAssigned = a.assignedTo || "ZZZ";
      const bAssigned = b.assignedTo || "ZZZ";
      return aAssigned.localeCompare(bAssigned);
    }
    if (sort.value === "deadline") {
      const aDeadline = a.deadline || "9999-12-31";
      const bDeadline = b.deadline || "9999-12-31";
      return aDeadline.localeCompare(bDeadline);
    }
    // Default sort by creation date (id contains timestamp)
    return a.id.localeCompare(b.id);
  });
  return filtered;
});
</script>
